name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: node 12 on ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.8.0
      - name: setup linux fs watchers
        if: runner.os == 'Linux'
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p
      - name: npm install
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install
      - name: code quality
        run: npm run eslint-check
      - name: code format
        run: npm run prettier-check
      - name: testing
        run: npm run test-with-coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: upload coverage
        run: npm run upload-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: publish package
        if: github.event_name == 'push'
        run: node ./.github/publish-package.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ensure github release
        if: github.event_name == 'push'
        run: node ./.github/ensure-github-release-for-package.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
