name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        # don't test on macos-latest because of
        # https://github.com/node-fetch/node-fetch/blob/8f406b789ab8464c195be87528c42dfcbd912893/src/index.js#L93
        # that is sometimes throwing ECONNRESET (that seems to be unhandled rejection)
        # maybe because of https://github.com/nodejs/node/issues/23169
        # or https://github.com/node-fetch/node-fetch/issues/309
        os: [macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        node: [15.10.0]
    runs-on: ${{ matrix.os }}
    name: test on ${{ matrix.os }} and node ${{ matrix.node }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: microsoft/playwright-github-action@v1
      - name: setup linux fs watchers
        if: runner.os == 'Linux'
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p
      - name: npm install
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install
      - name: code quality
        run: npm run eslint-check
      - name: code format
        run: npm run prettier-check
      - name: testing
        run: npm run test-with-coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: upload coverage
        run: npm run upload-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: [test]
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: npm install
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install
      - name: publish package
        run: node --experimental-top-level-await ./.github/release/publish-package.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ensure github release
        run: node ./.github/release/ensure-github-release-for-package.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
