name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [13.12.0]
    runs-on: ${{ matrix.os }}
    name: test on ${{ matrix.os }} and node ${{ matrix.node }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: setup linux fs watchers
        if: runner.os == 'Linux'
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p
      - name: install required linux packages
        if: runner.os == 'Linux'
        # see https://github.com/microsoft/playwright/blob/1f8508d1ed862f787d8e02a1fe4d1be186f69a81/.github/workflows/tests.yml#L25-L28
        # and https://github.com/microsoft/playwright/blob/1f8508d1ed862f787d8e02a1fe4d1be186f69a81/.github/workflows/tests.yml#L87-L90
        run: |
          sudo apt-get update
          sudo apt-get install libgbm-dev xvfb
          sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4 libxslt1.1
      - name: npm install
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install
      - name: code quality
        run: npm run eslint-check
      - name: code format
        run: npm run prettier-check
      - name: testing
        run: npm run test-with-coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: upload coverage
        run: npm run upload-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Non regression test for node 12.8
        if: runner.os == 'Linux'
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm install 12.8.0
          nvm use 12.8.0
          node ./script/test/test.cjs

  release:
    needs: [test]
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: npm install
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install --ignore-scripts
      - name: publish package
        run: node --no-warnings ./.github/release/publish-package.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ensure github release
        run: node --no-warnings ./.github/release/ensure-github-release-for-package.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
