name: performance_impact

on: pull_request_target

jobs:
  perf_impact:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [16.13.0]
    runs-on: ${{ matrix.os }}
    name: performance impact
    steps:
      - name: Setup git
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup npm
        run: npm install
      - name: Setup playwright
        run: npm run playwright-install
      - name: Report performance impact
        run: node --expose-gc ./.github/workflows/performance_impact/report_performance_impact.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
